"""
weekly-report: Markdown report generator for the Alpha Menu service.

Reuses the full pipeline from 03_generate_production_ratings.py — no code
duplication. Filters the output to show only algorithm-computed columns;
never exposes raw yfinance data or rating labels (legal compliance).

Usage:
    python3 04_generate_report.py                    # all tickers
    python3 04_generate_report.py --us                # US only
    python3 04_generate_report.py --eu                # European only
"""

import sys
import os
import numpy as np
import pandas as pd

# ── Import pipeline from script 03 (single source of truth) ──
sys.path.insert(0, os.path.dirname(__file__))
from sqlalchemy import create_engine
_mod03 = __import__('03_generate_production_ratings')
get_today_best_buys = _mod03.get_today_best_buys
deduplicate_by_company = _mod03.deduplicate_by_company
rank_normalize = _mod03.rank_normalize
CURRENT_PORTFOLIO = _mod03.CURRENT_PORTFOLIO


# ── DB engine from host path (matches Makefile convention) ──
def _make_engine():
    """Create a DB engine. Uses DATABASE_URL env, or local socket from PGPORT/PGHOST."""
    url = os.environ.get("DATABASE_URL")
    if url:
        return create_engine(url, pool_size=5, max_overflow=10)
    host = os.environ.get("PGHOST", "/home/oliver/aria-lite/.db_data")
    port = os.environ.get("PGPORT", "5432")
    url = f"postgresql+psycopg2:///alphapicks?host={host}&port={port}"
    return create_engine(url, pool_size=5, max_overflow=10)


# ── Markdown helpers ──


DISCLAIMER = (
    "*Generated by proprietary quantitative model. "
    "For informational purposes only. Not financial advice.*"
)


def fmt(val, decimals: int = 4) -> str:
    """Format a float to fixed decimals, or '---' if null.
    Passes strings through unchanged."""
    if isinstance(val, str):
        return val
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return "---"
    return f"{val:.{decimals}f}"


def md_table(df: pd.DataFrame, columns: list[str], top_n: int = 10) -> str:
    """Build a Markdown table for the given rows and columns."""
    if df.empty:
        return "  _(No stocks passed the filter this week)_\n"

    take = min(top_n, len(df))
    rows = df.head(take)

    # Human-readable header labels
    labels = {
        'final_score': 'Score',
        'mom_score': 'Mom',
        'acceleration': 'Accel',
        'near_high': 'Near High',
        'compound_score': 'Cmpd Score',
    }

    headers = [labels.get(c, c.replace('_', ' ').title()) for c in columns]

    # Separator row
    sep = ["---"] * len(columns)

    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join(sep) + " |")

    # Data rows
    for _, row in rows.iterrows():
        vals = []
        for c in columns:
            if c == "ticker":
                vals.append(str(row[c]))
            else:
                vals.append(fmt(row.get(c)))
        out.append("| " + " | ".join(vals) + " |")

    return "\n".join(out) + "\n" + "\n" + DISCLAIMER + "\n"


# ── Table builders ──

def table_momentum_leaders(picks: pd.DataFrame) -> str:
    """STRONG BUY rated picks, sorted by acceleration → near_high → score."""
    cols = ['final_score', 'mom_score', 'acceleration', 'near_high']
    sb = picks[picks['rating'].str.startswith('STRONG BUY')].copy()
    sb['accel_positive'] = sb['acceleration'].fillna(0) > 0
    sorted_sb = sb.sort_values(
        ['accel_positive', 'near_high', 'final_score'],
        ascending=[False, False, False]
    )
    return ("\n### Momentum Leaders\n\n"
            + "Top picks with positive near-term acceleration and proximity to highs.\n\n"
            + md_table(sorted_sb, ['ticker'] + cols, top_n=20))


def table_quality_compounders(picks: pd.DataFrame) -> str:
    """Pullback-quality + intact-thesis — 1-3 year horizon."""
    entries = ['compound_score', 'near_high']
    pool = picks[
        (picks['near_high'].fillna(0) >= 0.50)
        & (picks['near_high'].fillna(0) <= 0.88)
        & (picks['eps_rev'].fillna(0) > 0)
        & ~picks['rating'].str.startswith('SELL')
        & ~picks['rating'].str.startswith('HOLD')
    ].copy()

    pool['z_quality'] = rank_normalize(
        pool['rev_growth'].fillna(0).clip(0, 0.5) * 0.4
        + pool['op_margin'].fillna(0).clip(0, 0.3) * 0.3
        + pool['profit_margin'].fillna(0).clip(0, 0.3) * 0.3
    )
    pool['z_roe'] = rank_normalize(pool['roe'].fillna(0).clip(-0.5, 1.0))
    pool['z_safety'] = rank_normalize(-pool['debt_to_equity'].fillna(0).clip(0, 5))
    pool['z_fcf'] = rank_normalize(pool['fcf_yield'].fillna(0).clip(0, 0.3))
    pool['z_peg'] = rank_normalize(-pool['peg'].fillna(99).clip(0, 10))
    pool['z_revisions'] = rank_normalize(pool['eps_rev'].fillna(0))

    pool['compound_score'] = (
        pool['z_quality']   * 0.25
        + pool['z_roe']     * 0.15
        + pool['z_safety']  * 0.10
        + pool['z_fcf']     * 0.15
        + pool['z_peg']     * 0.15
        + pool['z_revisions'] * 0.20
    )

    sorted_pool = pool.sort_values('compound_score', ascending=False)
    return ("\n### Quality Compounders\n\n"
            + "Stocks in a pullback (50-88% of 52-week high) with intact business quality.\n\n"
            + md_table(sorted_pool, ['ticker'] + entries, top_n=20))


def table_technology_leaders(picks: pd.DataFrame) -> str:
    """Technology sector only."""
    tech = ['Technology', 'Semiconductors', 'Electronic Technology', 'Technology Services']
    cols = ['final_score', 'near_high', 'mom_score']
    pool = picks[
        picks['sector'].isin(tech)
        & (picks['rating'].str.startswith('STRONG BUY') | picks['rating'].str.startswith('BUY'))
    ]
    sorted_pool = pool.sort_values('final_score', ascending=False)
    return ("\n### Technology Sector Highlights\n\n"
            + "Leading technology picks.\n\n"
            + md_table(sorted_pool, ['ticker'] + cols, top_n=10))


def table_defensive_quality(picks: pd.DataFrame) -> str:
    """Defensive sectors at pullback entries."""
    def_sectors = ['Healthcare', 'Consumer Defensive', 'Utilities', 'Medical', 'Consumer Staples']
    cols = ['final_score', 'near_high']
    pool = picks[
        picks['sector'].isin(def_sectors)
        & (picks['near_high'].fillna(0) >= 0.50)
        & (picks['near_high'].fillna(0) <= 0.88)
        & ~picks['rating'].str.startswith('SELL')
        & ~picks['rating'].str.startswith('HOLD')
    ]
    sorted_pool = pool.sort_values('final_score', ascending=False)
    return ("\n### Defensive Quality Selections\n\n"
            + "Defensive-sector stocks in a pullback entry range.\n\n"
            + md_table(sorted_pool, ['ticker'] + cols, top_n=10))


def table_earnings_watch(picks: pd.DataFrame) -> str:
    """Positive estimate revisions only."""
    cols = ['final_score', 'near_high']
    pool = picks[picks['eps_rev'].notna() & (picks['eps_rev'] > 0)
                 & ~picks['rating'].str.startswith('SELL')
                 & ~picks['rating'].str.startswith('HOLD')]
    sorted_pool = pool.sort_values('final_score', ascending=False)
    return ("\n### Earnings Revision Watchlist\n\n"
            + "Stocks where analysts are raising estimates.\n\n"
            + md_table(sorted_pool, ['ticker'] + cols, top_n=10))


def table_value_momentum(picks: pd.DataFrame) -> str:
    """PEG < 1.0 + positive momentum + positive FCF."""
    cols = ['final_score', 'near_high', 'mom_score']
    pool = picks[
        (picks['peg'].fillna(99) < 1.0)
        & (picks['mom_score'].fillna(0) > 0)
        & (picks['fcf_yield'].fillna(0) > 0)
        & ~picks['rating'].str.startswith('SELL')
        & ~picks['rating'].str.startswith('HOLD')
    ]
    sorted_pool = pool.sort_values('final_score', ascending=False)
    return ("\n### Value & Momentum Composite\n\n"
            + "Stocks combining cheap valuation with positive momentum and cash generation.\n\n"
            + md_table(sorted_pool, ['ticker'] + cols, top_n=10))


def table_portfolio_highlights(status: pd.DataFrame) -> str:
    """Held positions still rated STRONG BUY or BUY."""
    cols = ['final_score', 'near_high', 'acceleration']
    pool = status[
        status['rating'].str.startswith('STRONG BUY') | status['rating'].str.startswith('BUY')
    ]
    sorted_pool = pool.sort_values('final_score', ascending=False)
    return ("\n### Current Holdings Scorecard\n\n"
            + "Positions held that still meet positive criteria.\n\n"
            + md_table(sorted_pool, ['ticker'] + cols, top_n=len(sorted_pool)))


def table_top_of_the_tops(picks: pd.DataFrame) -> str:
    """Top 10 absolute best stocks — STRONG BUY, tilted for 1-2 year hold.

    Blends momentum (timing) with business quality and valuation sanity (holding).
    Entry guard: near_high > 0.70 (trend alive, not dead money).

    Legally compliant: shows only algorithm-computed columns, no raw yfinance
    data and no rating labels.
    """
    cols = ['top_score', 'final_score', 'mom_score', 'near_high',
            'acceleration', 'eps_rev']

    pool = picks[
        picks['rating'].str.startswith('STRONG BUY')
        & (picks['near_high'].fillna(0) > 0.70)
        & (picks['near_high'].fillna(0) < 0.97)
    ].copy()

    if pool.empty:
        return ("\n### Top of the Tops\n\n"
                + "  _(No stocks pass all filters this week)_\n\n")

    # Normalise components for compositing
    pool['z_quality'] = rank_normalize(
        pool['rev_growth'].fillna(0).clip(0, 0.5) * 0.4
        + pool['op_margin'].fillna(0).clip(0, 0.3) * 0.3
        + pool['profit_margin'].fillna(0).clip(0, 0.3) * 0.3
    )
    pool['z_roe'] = rank_normalize(pool['roe'].fillna(0).clip(-0.5, 1.0))
    pool['z_peg'] = rank_normalize(-pool['peg'].fillna(99).clip(0, 10))
    pool['z_pe'] = rank_normalize(-pool['fwd_pe'].fillna(999).clip(0, 100))
    pool['z_revisions'] = rank_normalize(pool['eps_rev'].fillna(0))
    pool['z_accel'] = rank_normalize(pool['acceleration'].fillna(0))
    pool['z_final'] = rank_normalize(pool['final_score'].fillna(0))

    pool['top_score'] = (
        pool['z_final']     * 0.25   # momentum + quality anchor
        + pool['z_quality'] * 0.20   # revenue growth + margins
        + pool['z_roe']     * 0.10   # capital efficiency
        + pool['z_peg']     * 0.10   # valuation (growth-adjusted)
        + pool['z_pe']      * 0.10   # valuation (raw)
        + pool['z_revisions'] * 0.15  # thesis intact
        + pool['z_accel']   * 0.10    # near-term catalyst
    )

    sorted_pool = pool.sort_values('top_score', ascending=False).head(10)
    return ("\n### Top of the Tops\n\n"
            + "Top 10 absolute best stocks — algorithm scores only.\n"
            + "No raw data or ratings displayed (legal compliance).\n\n"
            + md_table(sorted_pool, ['ticker'] + cols, top_n=10))


# ── Main ──

def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(
        description="Generate Markdown report tables from the alpha pipeline."
    )
    parser.add_argument("--us", action="store_true", help="US tickers only")
    parser.add_argument("--eu", action="store_true", help="European tickers only")
    args = parser.parse_args()

    print(f"# Weekly Alpha Report — {pd.Timestamp.today().strftime('%Y-%m-%d')}")
    print()

    picks, status = get_today_best_buys(
        _make_engine(), us_only=args.us, eu_only=args.eu
    )

    picks = deduplicate_by_company(picks, _make_engine())

    if picks is None:
        print("No data returned from pipeline.")
        sys.exit(1)

    # Table 3 – Momentum Leaders
    print(table_momentum_leaders(picks))

    # Table 4 – Quality Compounders
    print(table_quality_compounders(picks))

    # Table 5 – Technology Leaders
    print(table_technology_leaders(picks))

    # Table 6 – Defensive Quality
    print(table_defensive_quality(picks))

    # Table 7 – Earnings Revision Watchlist
    print(table_earnings_watch(picks))

    # Table 8 – Value & Momentum
    print(table_value_momentum(picks))

    # Table 9 – Portfolio Highlights
    if status is not None:
        print(table_portfolio_highlights(status))

    # Table 10 – Top of the Tops
    print(table_top_of_the_tops(picks))


if __name__ == "__main__":
    main()